const config = {
        type: Phaser.AUTO,
            width: 800,
                height: 600,
                    parent: 'game-container',
                        physics: {
                                default: 'arcade',
                                        arcade: { gravity: { y: 300 }, debug: false }
                                            },
                                                scene: {
                                                        preload: preload,
                                                                create: create,
                                                                        update: update
                                                                            }
                                                                            };

                                                                            const game = new Phaser.Game(config);
                                                                            let player, enemy, cursors, spaceKey, playerHealthText, enemyHealthText;
                                                                            let leftBtn, rightBtn, jumpBtn, punchBtn; // Tombol virtual

                                                                            function preload() {
                                                                                // Tidak perlu load gambar
                                                                                }

                                                                                function create() {
                                                                                    // Background game
                                                                                        this.add.rectangle(400, 300, 800, 600, 0x87CEEB); // Langit biru

                                                                                            // Tambah tanah
                                                                                                this.add.rectangle(400, 580, 800, 50, 0x8B4513); // Coklat

                                                                                                    // Buat pemain (rectangle merah)
                                                                                                        player = this.physics.add.sprite(100, 450, null);
                                                                                                            player.setDisplaySize(50, 50);
                                                                                                                player.setTint(0xff0000);
                                                                                                                    player.setCollideWorldBounds(true);
                                                                                                                        player.health = 100;

                                                                                                                            // Buat musuh (rectangle biru)
                                                                                                                                enemy = this.physics.add.sprite(700, 450, null);
                                                                                                                                    enemy.setDisplaySize(50, 50);
                                                                                                                                        enemy.setTint(0x0000ff);
                                                                                                                                            enemy.setCollideWorldBounds(true);
                                                                                                                                                enemy.health = 100;

                                                                                                                                                    // Kontrol keyboard
                                                                                                                                                        cursors = this.input.keyboard.createCursorKeys();
                                                                                                                                                            spaceKey = this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.SPACE);

                                                                                                                                                                // Tombol virtual untuk HP (di bawah canvas)
                                                                                                                                                                    leftBtn = this.add.circle(100, 650, 40, 0xcccccc).setInteractive(); // Kiri
                                                                                                                                                                        rightBtn = this.add.circle(200, 650, 40, 0xcccccc).setInteractive(); // Kanan
                                                                                                                                                                            jumpBtn = this.add.circle(300, 650, 40, 0x00ff00).setInteractive(); // Lompat (hijau)
                                                                                                                                                                                punchBtn = this.add.circle(400, 650, 40, 0xff0000).setInteractive(); // Pukul (merah)

                                                                                                                                                                                    // Label tombol
                                                                                                                                                                                        this.add.text(100, 640, 'Kiri', { fontSize: '14px', fill: '#000' }).setOrigin(0.5);
                                                                                                                                                                                            this.add.text(200, 640, 'Kanan', { fontSize: '14px', fill: '#000' }).setOrigin(0.5);
                                                                                                                                                                                                this.add.text(300, 640, 'Lompat', { fontSize: '14px', fill: '#000' }).setOrigin(0.5);
                                                                                                                                                                                                    this.add.text(400, 640, 'Pukul', { fontSize: '14px', fill: '#000' }).setOrigin(0.5);

                                                                                                                                                                                                        // Event tombol virtual
                                                                                                                                                                                                            leftBtn.on('pointerdown', () => player.setVelocityX(-160));
                                                                                                                                                                                                                leftBtn.on('pointerup', () => player.setVelocityX(0));
                                                                                                                                                                                                                    rightBtn.on('pointerdown', () => player.setVelocityX(160));
                                                                                                                                                                                                                        rightBtn.on('pointerup', () => player.setVelocityX(0));
                                                                                                                                                                                                                            jumpBtn.on('pointerdown', () => { if (player.body.touching.down) player.setVelocityY(-330); });
                                                                                                                                                                                                                                punchBtn.on('pointerdown', () => {
                                                                                                                                                                                                                                        if (Phaser.Math.Distance.Between(player.x, player.y, enemy.x, enemy.y) < 100) {
                                                                                                                                                                                                                                                    enemy.health -= 10;
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                    // UI Health
                                                                                                                                                                                                                                                                        playerHealthText = this.add.text(10, 10, 'Health Pemain: ' + player.health, { fontSize: '20px', fill: '#000' });
                                                                                                                                                                                                                                                                            enemyHealthText = this.add.text(600, 10, 'Health Musuh: ' + enemy.health, { fontSize: '20px', fill: '#000' });
                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                            function update() {
                                                                                                                                                                                                                                                                                // Reset velocity horizontal jika tidak tekan tombol
                                                                                                                                                                                                                                                                                    if (!leftBtn.isDown && !rightBtn.isDown) {
                                                                                                                                                                                                                                                                                            player.setVelocityX(0);
                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                    // Gerak pemain (keyboard sebagai backup)
                                                                                                                                                                                                                                                                                                        if (cursors.left.isDown) {
                                                                                                                                                                                                                                                                                                                player.setVelocityX(-160);
                                                                                                                                                                                                                                                                                                                    } else if (cursors.right.isDown) {
                                                                                                                                                                                                                                                                                                                            player.setVelocityX(160);
                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                    if (cursors.up.isDown && player.body.touching.down) {
                                                                                                                                                                                                                                                                                                                                            player.setVelocityY(-330);
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                    // Pukul dengan Space
                                                                                                                                                                                                                                                                                                                                                        if (Phaser.Input.Keyboard.JustDown(spaceKey) && Phaser.Math.Distance.Between(player.x, player.y, enemy.x, enemy.y) < 100) {
                                                                                                                                                                                                                                                                                                                                                                enemy.health -= 10;
                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                        // AI musuh
                                                                                                                                                                                                                                                                                                                                                                            if (enemy.x < player.x - 50) {
                                                                                                                                                                                                                                                                                                                                                                                    enemy.setVelocityX(50);
                                                                                                                                                                                                                                                                                                                                                                                        } else if (enemy.x > player.x + 50) {
                                                                                                                                                                                                                                                                                                                                                                                                enemy.setVelocityX(-50);
                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                            enemy.setVelocityX(0);
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                    // Update UI
                                                                                                                                                                                                                                                                                                                                                                                                                        playerHealthText.setText('Health Pemain: ' + player.health);
                                                                                                                                                                                                                                                                                                                                                                                                                            enemyHealthText.setText('Health Musuh: ' + enemy.health);

                                                                                                                                                                                                                                                                                                                                                                                                                                // Cek kemenangan
                                                                                                                                                                                                                                                                                                                                                                                                                                    if (player.health <= 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            this.add.text(400, 300, 'Kalah!', { fontSize: '40px', fill: '#ff0000' }).setOrigin(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    this.physics.pause();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else if (enemy.health <= 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                this.add.text(400, 300, 'Menang!', { fontSize: '40px', fill: '#00ff00' }).setOrigin(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        this.physics.pause();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
}