// Cek jika Phaser load
if (typeof Phaser === 'undefined') {
    document.getElementById('debug').innerText = 'Error: Phaser tidak load. Cek koneksi internet.';
    } else {
        document.getElementById('debug').innerText = 'Phaser loaded. Starting game...';

            const config = {
                    type: Phaser.AUTO,
                            width: 800,
                                    height: 600,
                                            parent: 'game-container',
                                                    physics: {
                                                                default: 'arcade',
                                                                            arcade: { gravity: { y: 300 }, debug: false }
                                                                                    },
                                                                                            scene: {
                                                                                                        preload: preload,
                                                                                                                    create: create,
                                                                                                                                update: update
                                                                                                                                        }
                                                                                                                                            };

                                                                                                                                                const game = new Phaser.Game(config);
                                                                                                                                                    let player, enemy, playerHealthText, enemyHealthText;

                                                                                                                                                        function preload() {
                                                                                                                                                                // Kosong, tidak perlu gambar
                                                                                                                                                                    }

                                                                                                                                                                        function create() {
                                                                                                                                                                                // Debug: Konfirmasi scene berjalan
                                                                                                                                                                                        this.add.text(10, 50, 'Game Loaded! Karakter akan muncul.', { fontSize: '16px', fill: '#000' });

                                                                                                                                                                                                // Background biru
                                                                                                                                                                                                        this.add.rectangle(400, 300, 800, 600, 0x87CEEB);

                                                                                                                                                                                                                // Tanah coklat
                                                                                                                                                                                                                        this.add.rectangle(400, 580, 800, 50, 0x8B4513);

                                                                                                                                                                                                                                // Pemain: Rectangle merah besar agar jelas
                                                                                                                                                                                                                                        player = this.physics.add.sprite(100, 450, null);
                                                                                                                                                                                                                                                player.setDisplaySize(60, 60); // Lebih besar
                                                                                                                                                                                                                                                        player.setTint(0xff0000); // Merah terang
                                                                                                                                                                                                                                                                player.setCollideWorldBounds(true);
                                                                                                                                                                                                                                                                        player.health = 100;

                                                                                                                                                                                                                                                                                // Musuh: Rectangle biru besar
                                                                                                                                                                                                                                                                                        enemy = this.physics.add.sprite(700, 450, null);
                                                                                                                                                                                                                                                                                                enemy.setDisplaySize(60, 60);
                                                                                                                                                                                                                                                                                                        enemy.setTint(0x0000ff); // Biru terang
                                                                                                                                                                                                                                                                                                                enemy.setCollideWorldBounds(true);
                                                                                                                                                                                                                                                                                                                        enemy.health = 100;

                                                                                                                                                                                                                                                                                                                                // UI Health
                                                                                                                                                                                                                                                                                                                                        playerHealthText = this.add.text(10, 10, 'Health Pemain: ' + player.health, { fontSize: '20px', fill: '#000' });
                                                                                                                                                                                                                                                                                                                                                enemyHealthText = this.add.text(600, 10, 'Health Musuh: ' + enemy.health, { fontSize: '20px', fill: '#000' });

                                                                                                                                                                                                                                                                                                                                                        // Kontrol touch sederhana: Sentuh layar untuk gerak/pukul
                                                                                                                                                                                                                                                                                                                                                                this.input.on('pointerdown', (pointer) => {
                                                                                                                                                                                                                                                                                                                                                                            if (pointer.x < 400) {
                                                                                                                                                                                                                                                                                                                                                                                            player.setVelocityX(-160); // Kiri
                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                        player.setVelocityX(160); // Kanan
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                if (pointer.y < 300 && player.body.touching.down) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                player.setVelocityY(-330); // Lompat
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Pukul jika dekat
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (Phaser.Math.Distance.Between(player.x, player.y, enemy.x, enemy.y) < 100) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    enemy.health -= 10;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Update debug
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('debug').innerText = 'Game ready! Sentuh layar untuk main.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function update() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // AI musuh
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (enemy.x < player.x - 50) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            enemy.setVelocityX(50);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else if (enemy.x > player.x + 50) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                enemy.setVelocityX(-50);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    enemy.setVelocityX(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Update health
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            playerHealthText.setText('Health Pemain: ' + player.health);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    enemyHealthText.setText('Health Musuh: ' + enemy.health);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Cek kemenangan
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (player.health <= 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                this.add.text(400, 300, 'Kalah!', { fontSize: '40px', fill: '#ff0000' }).setOrigin(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            this.physics.pause();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else if (enemy.health <= 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                this.add.text(400, 300, 'Menang!', { fontSize: '40px', fill: '#00ff00' }).setOrigin(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            this.physics.pause();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }