if (typeof Phaser === 'undefined') {
        alert('Error: Phaser tidak load. Cek koneksi internet.');
        } else {
            const config = {
                    type: Phaser.AUTO,
                            width: 800,
                                    height: 600,
                                            parent: 'game-container',
                                                    physics: {
                                                                default: 'arcade',
                                                                            arcade: { gravity: { y: 300 }, debug: false }
                                                                                    },
                                                                                            scene: {
                                                                                                        preload: preload,
                                                                                                                    create: create,
                                                                                                                                update: update
                                                                                                                                        }
                                                                                                                                            };

                                                                                                                                                const game = new Phaser.Game(config);
                                                                                                                                                    let player, enemy, playerHealthText, enemyHealthText, leftBtn, rightBtn, jumpBtn, punchBtn, cursors, spaceKey, gameOver = false;

                                                                                                                                                        function preload() {
                                                                                                                                                                // Tidak ada preload, gunakan emoji sebagai karakter
                                                                                                                                                                    }

                                                                                                                                                                        function create() {
                                                                                                                                                                                // Background
                                                                                                                                                                                        this.add.rectangle(400, 300, 800, 600, 0x87CEEB); // Biru langit
                                                                                                                                                                                                this.add.rectangle(400, 580, 800, 50, 0x8B4513); // Tanah coklat

                                                                                                                                                                                                        // Pemain: Emoji 👊
                                                                                                                                                                                                                player = this.physics.add.sprite(100, 450, null);
                                                                                                                                                                                                                        player.setDisplaySize(60, 60);
                                                                                                                                                                                                                                player.setCollideWorldBounds(true);
                                                                                                                                                                                                                                        player.health = 100;
                                                                                                                                                                                                                                                player.emoji = this.add.text(player.x, player.y, '👊', { fontSize: '50px' }).setOrigin(0.5);

                                                                                                                                                                                                                                                        // Musuh: Emoji 🤖
                                                                                                                                                                                                                                                                enemy = this.physics.add.sprite(700, 450, null);
                                                                                                                                                                                                                                                                        enemy.setDisplaySize(60, 60);
                                                                                                                                                                                                                                                                                enemy.setCollideWorldBounds(true);
                                                                                                                                                                                                                                                                                        enemy.health = 100;
                                                                                                                                                                                                                                                                                                enemy.emoji = this.add.text(enemy.x, enemy.y, '🤖', { fontSize: '50px' }).setOrigin(0.5);

                                                                                                                                                                                                                                                                                                        // Kontrol keyboard
                                                                                                                                                                                                                                                                                                                cursors = this.input.keyboard.createCursorKeys();
                                                                                                                                                                                                                                                                                                                        spaceKey = this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.SPACE);

                                                                                                                                                                                                                                                                                                                                // Tombol virtual untuk HP (di dalam game container)
                                                                                                                                                                                                                                                                                                                                        leftBtn = this.add.circle(150, 550, 40, 0xcccccc).setInteractive();
                                                                                                                                                                                                                                                                                                                                                rightBtn = this.add.circle(250, 550, 40, 0xcccccc).setInteractive();
                                                                                                                                                                                                                                                                                                                                                        jumpBtn = this.add.circle(350, 550, 40, 0x00ff00).setInteractive();
                                                                                                                                                                                                                                                                                                                                                                punchBtn = this.add.circle(450, 550, 40, 0xff0000).setInteractive();

                                                                                                                                                                                                                                                                                                                                                                        // Label tombol
                                                                                                                                                                                                                                                                                                                                                                                this.add.text(150, 540, 'Kiri', { fontSize: '14px', fill: '#000' }).setOrigin(0.5);
                                                                                                                                                                                                                                                                                                                                                                                        this.add.text(250, 540, 'Kanan', { fontSize: '14px', fill: '#000' }).setOrigin(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                this.add.text(350, 540, 'Lompat', { fontSize: '14px', fill: '#000' }).setOrigin(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                        this.add.text(450, 540, 'Pukul', { fontSize: '14px', fill: '#000' }).setOrigin(0.5);

                                                                                                                                                                                                                                                                                                                                                                                                                // Event tombol virtual
                                                                                                                                                                                                                                                                                                                                                                                                                        leftBtn.on('pointerdown', () => player.setVelocityX(-160));
                                                                                                                                                                                                                                                                                                                                                                                                                                leftBtn.on('pointerup', () => player.setVelocityX(0));
                                                                                                                                                                                                                                                                                                                                                                                                                                        rightBtn.on('pointerdown', () => player.setVelocityX(160));
                                                                                                                                                                                                                                                                                                                                                                                                                                                rightBtn.on('pointerup', () => player.setVelocityX(0));
                                                                                                                                                                                                                                                                                                                                                                                                                                                        jumpBtn.on('pointerdown', () => { if (player.body.touching.down) player.setVelocityY(-330); });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                punchBtn.on('pointerdown', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (Phaser.Math.Distance.Between(player.x, player.y, enemy.x, enemy.y) < 100) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            enemy.health -= 10;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Efek pukul: Kedip musuh
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            enemy.emoji.setTint(0xff0000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            this.time.delayedCall(200, () => enemy.emoji.clearTint());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // UI Health
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                playerHealthText = this.add.text(10, 10, 'Health Pemain: ' + player.health, { fontSize: '20px', fill: '#000' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        enemyHealthText = this.add.text(600, 10, 'Health Musuh: ' + enemy.health, { fontSize: '20px', fill: '#000' });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Restart button (tampil saat game over)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('restart-btn').addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    location.reload(); // Reload halaman untuk restart
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function update() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (gameOver) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Update posisi emoji sesuai sprite
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            player.emoji.setPosition(player.x, player.y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    enemy.emoji.setPosition(enemy.x, enemy.y);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Reset velocity horizontal jika tidak tekan tombol
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!leftBtn.isDown && !rightBtn.isDown) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                player.setVelocityX(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Gerak pemain (keyboard sebagai backup)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (cursors.left.isDown || this.input.keyboard.checkDown(this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.A))) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    player.setVelocityX(-160);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (cursors.right.isDown || this.input.keyboard.checkDown(this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.D))) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        player.setVelocityX(160);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (cursors.up.isDown && player.body.touching.down) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    player.setVelocityY(-330);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Pukul dengan Space
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (Phaser.Input.Keyboard.JustDown(spaceKey) && Phaser.Math.Distance.Between(player.x, player.y, enemy.x, enemy.y) < 100) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        enemy.health -= 10;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    enemy.emoji.setTint(0xff0000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                this.time.delayedCall(200, () => enemy.emoji.clearTint());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // AI musuh
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (enemy.x < player.x - 50) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    enemy.setVelocityX(50);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (enemy.x > player.x + 50) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        enemy.setVelocityX(-50);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            enemy.setVelocityX(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Update UI
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    playerHealthText.setText('Health Pemain: ' + player.health);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            enemyHealthText.setText('Health Musuh: ' + enemy.health);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Cek kemenangan
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (player.health <= 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        this.add.text(400, 300, 'Kalah!', { fontSize: '40px', fill: '#ff0000' }).setOrigin(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gameOver = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById('restart-btn').style.display = 'block';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            this.physics.pause();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else if (enemy.health <= 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                this.add.text(400, 300, 'Menang!', { fontSize: '40px', fill: '#00ff00' }).setOrigin(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gameOver = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('restart-btn').style.display = 'block';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    this.physics.pause();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
}